/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#include <RtORB/cdrStream.h>
#define CONST const
#define SS2012FPGA_COMMON
#include "SS2012FPGA.h"

#ifndef ORBIT_IDL_C_IMODULE_SS2012FPGA
void
_RtORB_impl_jp_ac_utsunomiya_is_SS2012FPGA_setMotorTorque
   (CORBA_jp_ac_utsunomiya_is_SS2012FPGA obj, void **result,
    CORBA_Class_Method * m, void **argv, CORBA_Environment * env,
    void (*_impl_setMotorTorque) (PortableServer_Servant _servant,
				  CORBA_long motorID, CORBA_long maxTorque,
				  CORBA_long torque, CORBA_Environment * ev))
{
   _impl_setMotorTorque(obj, *(CORBA_long *) argv[0], *(CORBA_long *) argv[1],
			*(CORBA_long *) argv[2], env);
}

void
_RtORB_impl_jp_ac_utsunomiya_is_SS2012FPGA_playAlarmSound
   (CORBA_jp_ac_utsunomiya_is_SS2012FPGA obj, void **result,
    CORBA_Class_Method * m, void **argv, CORBA_Environment * env,
    void (*_impl_playAlarmSound) (PortableServer_Servant _servant,
				  CORBA_Environment * ev))
{
   _impl_playAlarmSound(obj, env);
}

void
_RtORB_impl_jp_ac_utsunomiya_is_SS2012FPGA_getAlarmSwitchState
   (CORBA_jp_ac_utsunomiya_is_SS2012FPGA obj, void **result,
    CORBA_Class_Method * m, void **argv, CORBA_Environment * env,
    CORBA_long(*_impl_getAlarmSwitchState) (PortableServer_Servant _servant,
					    CORBA_Environment * ev))
{
   *(CORBA_long *) result = _impl_getAlarmSwitchState(obj, env);
}

void
_RtORB_impl_jp_ac_utsunomiya_is_SS2012FPGA_sendIrDAdata
   (CORBA_jp_ac_utsunomiya_is_SS2012FPGA obj, void **result,
    CORBA_Class_Method * m, void **argv, CORBA_Environment * env,
    void (*_impl_sendIrDAdata) (PortableServer_Servant _servant,
				CORBA_long data, CORBA_Environment * ev))
{
   _impl_sendIrDAdata(obj, *(CORBA_long *) argv[0], env);
}

#endif
#if ( (TC_IMPL_TC_jp_ac_utsunomiya_is_SS2012FPGA_0 == 'S') \
&& (TC_IMPL_TC_jp_ac_utsunomiya_is_SS2012FPGA_1 == 'S') \
&& (TC_IMPL_TC_jp_ac_utsunomiya_is_SS2012FPGA_2 == '2') \
&& (TC_IMPL_TC_jp_ac_utsunomiya_is_SS2012FPGA_3 == '0') \
&& (TC_IMPL_TC_jp_ac_utsunomiya_is_SS2012FPGA_4 == '1') \
&& (TC_IMPL_TC_jp_ac_utsunomiya_is_SS2012FPGA_5 == '2') \
&& (TC_IMPL_TC_jp_ac_utsunomiya_is_SS2012FPGA_6 == 'F') \
&& (TC_IMPL_TC_jp_ac_utsunomiya_is_SS2012FPGA_7 == 'P') \
&& (TC_IMPL_TC_jp_ac_utsunomiya_is_SS2012FPGA_8 == 'G') \
&& (TC_IMPL_TC_jp_ac_utsunomiya_is_SS2012FPGA_9 == 'A') \
) && !defined(TC_DEF_TC_jp_ac_utsunomiya_is_SS2012FPGA)
#define TC_DEF_TC_jp_ac_utsunomiya_is_SS2012FPGA 1
/***   TC_jp_ac_utsunomiya_is_SS2012FPGA  ***/
__attribute__ ((weak))
#ifdef ORBIT_IDL_C_IMODULE_SS2012FPGA
     static
#endif
     struct CORBA_TypeCode_struct TC_jp_ac_utsunomiya_is_SS2012FPGA_struct = {
	NULL,			// parent 
	tk_objref,		// kind 
	"IDL:jp/ac/utsunomiya/is/SS2012FPGA:1.0",	// repository_id 
	"SS2012FPGA",		// identifier 
	0,			// member_count  
	NULL,			// member_name
	NULL,			// member_type
	NULL,			// member_label
	CORBA_OBJECT_NIL,	// discriminator  
	-1,			// default_index 
	0,			// length 
	NULL,			// content_type 
	0, 0,			// fixed_digits, fixed_scale 
	NULL,			// *member_visibility 
	NULL,			// type_modifier 
	NULL,			// *concrete_base_type 
	4,			// size
	Align_pointer
     };
#endif

#ifndef ORBIT_IDL_C_IMODULE_SS2012FPGA
CORBA_unsigned_long jp_ac_utsunomiya_is_SS2012FPGA__classid = 0;
#endif

/* Interface type data */

static CORBA_IArg jp_ac_utsunomiya_is_SS2012FPGA_setMotorTorque__arginfo[] = {
   {TC_CORBA_long, CORBA_I_ARG_IN, "motorID"},
   {TC_CORBA_long, CORBA_I_ARG_IN, "maxTorque"},
   {TC_CORBA_long, CORBA_I_ARG_IN, "torque"}
};

static CORBA_IArg jp_ac_utsunomiya_is_SS2012FPGA_sendIrDAdata__arginfo[] = {
   {TC_CORBA_long, CORBA_I_ARG_IN, "data"}
};

#ifdef ORBIT_IDL_C_IMODULE_SS2012FPGA
static
#endif
CORBA_Class_Method jp_ac_utsunomiya_is_SS2012FPGA__methods[]
   __attribute__ ((weak)) = {
   {
   "setMotorTorque",
	 TC_void,
	 3, jp_ac_utsunomiya_is_SS2012FPGA_setMotorTorque__arginfo, 0, NULL}
   , {
   "playAlarmSound", TC_void, 0, NULL, 0, NULL}
   , {
   "getAlarmSwitchState", TC_CORBA_long, 0, NULL, 0, NULL}
   , {
   "sendIrDAdata",
	 TC_void,
	 1, jp_ac_utsunomiya_is_SS2012FPGA_sendIrDAdata__arginfo, 0, NULL}
};

static char *jp_ac_utsunomiya_is_SS2012FPGA__base_itypes[] = {
   "IDL:omg.org/CORBA/Object:1.0"
};

#ifdef ORBIT_IDL_C_IMODULE_SS2012FPGA
static
#endif
   CORBA_Class_Impl jp_ac_utsunomiya_is_SS2012FPGA__imp
   __attribute__ ((weak)) = {
TC_jp_ac_utsunomiya_is_SS2012FPGA, "jp_ac_utsunomiya_is_SS2012FPGA", 4,
      jp_ac_utsunomiya_is_SS2012FPGA__methods, 1,
      (char **) jp_ac_utsunomiya_is_SS2012FPGA__base_itypes};

#ifdef __cplusplus		/* cc_output_methods */
#endif /* __cplusplus */
